const BASE_THRESHOLD = 50;
const BASE_MULTIPLIER = 1;

const TOP_THRESHOLD = 100;
const TOP_MULTIPLIER = 2;

const API_RESPONSE_CODES = {
    SUCCESS: 200,
    SERVER_ERROR: 500,
    NOT_FOUND: 404,
    INVALID_REQUEST: 400,
};

const NANO_ID_SIZE = 4;

export {
    BASE_THRESHOLD,
    BASE_MULTIPLIER,
    TOP_THRESHOLD,
    TOP_MULTIPLIER,
    API_RESPONSE_CODES,
    NANO_ID_SIZE,
};
